version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_service
    ports:
      - '5000:5000'
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend:/app
    restart: unless-stopped
    command: npm start

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_service
    ports:
      - '3000:80'
    environment:
      - NODE_ENV=production
    restart: unless-stopped
